services:
  - type: web
    name: data-center-viz-llm-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: GOOGLE_API_KEY
        sync: false
